var message = ("Hello World!")
var myName = ("my name is: Muhammad Aayan shaikh")
var age = ("I'm 19yo")
var certified = ("Im certified UI and front-end-developer")
var myEmail = ("my email is: muhammadaayanshaikhforbusiness@gmail.com")
var book = ("im trying to learn from book A smarter way to learn JavaScript!")
var Inpage = ("Yah! i can write HTML content through JavaScript")
alert(message)
alert(myName)
alert(age)
alert(certified)
alert(myEmail)
alert(book)
document.write(Inpage)
alert("▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬")